name: code_mobility
description: A library for code mobility with Dart.
version: 0.0.1
author: Daniel Bälz <me@dbaelz.de>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  http: "^0.11.3"
  logging: '^0.11.1'
  path: '^1.3.6'
  rpc: '^0.5.0'
  uuid: '^0.5.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
