name: code_mobility
description: A library for code mobility with Dart.
version: 1.0.0
author: Daniel Bälz <me@dbaelz.de>
homepage: https://github.com/dbaelz/code_mobility

environment:
  sdk: '>=1.13.0 <2.0.0'

dependencies:
  http: "^0.11.3"
  logging: '^0.11.1'
  path: '^1.3.6'
  rpc: '^0.5.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
